// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"URLShortener/app"
	"URLShortener/controller/store_controller"
	"URLShortener/repository/store_repository"
	"URLShortener/service/store_service"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
)

// Injectors from injector.go:

func InitializeServer() *gin.Engine {
	client := app.NewRedisClient()
	storeRepository := store_repository.NewStoreRepository()
	validate := validator.New()
	storeService := store_service.NewStoreService(storeRepository, validate)
	storeContoller := store_controller.NewStoreController(storeService)
	engine := app.NewRouter(client, storeContoller)
	return engine
}
